### ISSUE TITLE
Mux.Dial and Mux.DialUTP both return *Conn, bet you meant net.Conn for the former

### ISSUE THREAD

**Issue by tv42** [calmh/dst#1]

**Comment by calmh** [comment]
Indeed!

(This is all very unstable yet, I recommend not running this. I published it on github so that I can run automated tests on it...)

**Comment by tv42** [comment]
I am definitely sticking to TCP/HTTP for a while, but keen to study MinimaLT/CurveCP/UDP/uTP style protocols for later use..
